version: '3.8'

services:
    app-diplom:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.php
        image: diplom-app-image
        container_name: diplom-app
        restart: unless-stopped
        tty: true
        environment:
        - "DB_PORT=${DB_PORT}"
        - "DB_HOST=${DB_HOST}"
        working_dir: /var/www
        networks:
        - diplom-network
        volumes:
        - .:/var/www
        ports:
        - "3000:3000"  # Экспонирование порта для Vite Dev Server

    nginx-diplom:
        image: nginx:alpine
        container_name: diplom-nginx
        restart: unless-stopped
        tty: true
        ports:
        - "806:80"
#        - "4436:443"
        networks:
        - diplom-network
        volumes:
        - .:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - ./docker/nginx/ssl:/etc/nginx/ssl

    mysql-diplom:
        image: mysql:8.0
        container_name: ${DB_HOST}
        restart: unless-stopped
        tty: true
        ports:
        - "33065:3306"
        networks:
        - diplom-network
        environment:
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        - "MYSQL_USER=${DB_USERNAME}"
        - "MYSQL_PASSWORD=${DB_PASSWORD}"
        - "MYSQL_DATABASE=${DB_DATABASE}"
        - "MYSQL_TCP_PORT=${DB_PORT}"
        volumes:
        - ./docker/mysql/db:/var/lib/mysql

networks:
    diplom-network:
        driver: bridge
